@isTest
public class homeloan_classTest{ 
   /*			@isTest static void homeloan_class_Test(){        
        	Account a = new Account(Name='Test account');
        	insert a;
        
        	opportunity opp = new opportunity();           
         	opp.AccountId=a.Id;
         	opp.Name='TestOpp';
         	opp.StageName='Personal Information';
         	opp.CloseDate=Date.today();
         	opp.Loan_Sanction_Date__c=Date.today(); 
         	opp.Approved_Loan_Amount__c=3000;
         	opp.Approved_ROI__c=300.70;
         	opp.Approved_Tenure__c=12;         
         	insert opp;
       
     //   	Opportunity o = new Opportunity(Name='OppTest',StageName='Personal Information',AccountId = a.id, Approved_Loan_Amount__c = 100000, Approved_Tenure__c = 100, closeDate=Date.today()+100);
     //   	insert o;  
            
       		Contact con = new Contact(LastName='TestContact', AccountId = a.Id,email='pranjali_watkar@persistent.com',MobilePhone='1555555555',MailingCity='Pune',
                                      MailingCountry='India',MailingState='Maharashtra',MailingPostalcode='440022');
        	insert con;  
            
           	homeloan_class h =new homeloan_class(opp);  
          
 		
    } */     
}